name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Test qt error
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      name: Install Python 3.7
      with:
        python-version: "3.7"
    - name: Install ubuntu libraries
      run: sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0
    - name: Install dependencies
      run: |
        python -m pip install tox

    - name: Test PartSeg
      run: tox